-
  name: Deploy a mysql DB
  hosts: nodes #host group is same in this case
  roles:
    - python
    - mysql_db
    
-
  name: Deploy a web server
  hosts: nodes
  roles:
    - python
    - flask_web