-
  name: Deploy a web application
  hosts: nodes
  become: true
  tasks:
    - name: Install dependencies
      dnf: 
        name: python
        state: present
      with_items:
       - python
       - python-setuptools
       - python-dev
       - build-essential
       - python-pip
       - python-mysqldb

    - include: tasks/deploy_db.yml
    - include: tasks/deploy_web.yml
