-
  name: Deploy a mysql DB
  hosts: nodes #host group is same in this case
  roles:
    - python
    - mysql_db
    
-
  name: Deploy a web server
  hosts: nodes
  roles:
    - python
    - flask_web

-
  name: Monitor Web Application for 6 Minutes
  hosts: web_server
  command: /opt/monitor_webapp.py
  async: 360
  poll: 0
  register: webapp_result

-
  name: Monitor Database for 6 Minutes
  hosts: db_server
  command: /opt/monitor_database.py
  async: 360
  poll: 0
  register: database_result